# 端口号配置
server:
  port: 8100

#  日志配置
logging:
  file:
    path: ./commonLog
  config: classpath:logback-spring.xml
  level:
    com:
      superjson:
        common:
          mapper: info

# 配置Redis
spring:
  devtools:
    restart:
      enabled: true
  redis:
    client-name: redis
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 30000
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/common?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    #mybatisplus配置
mybatis:
  typeAliasesPackage: com.superjson.common
  mapperLocations: classpath:mapping/*Mapper.xml
